language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
before_install:
 - pip install -r requirements.txt --use-mirrors
script: python -m unittest tests/__init__.py -v
services:
    - redis-server
